import assert from 'node:assert/strict';
import { cp, mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const npmCli = process.env.npm_execpath;
if (!npmCli) throw new Error('Run this check with npm run test:package.');
const npm = (args, cwd = root) => execFileSync(process.execPath, [npmCli, ...args], { cwd, encoding: 'utf8' });
const packed = JSON.parse(npm(['pack', './package-dist', '--pack-destination', 'artifacts', '--json']))[0];
const tarball = join(root, 'artifacts', packed.filename);
assert(!packed.files.some(file => file.path.includes('data/hamburg/roads/tiles/')));
assert(packed.files.some(file => file.path.endsWith('.wasm')));
assert(packed.files.some(file => file.path === 'WASM-NOTICES.md'));
const consumer = await mkdtemp(join(tmpdir(), 'webcityeditor-consumer-'));
await cp(join(root, 'examples/embedded'), consumer, { recursive: true, filter: source => !source.includes('node_modules') && !source.includes('webcityeditor-assets') });
const manifest = JSON.parse(await readFile(join(consumer, 'package.json'), 'utf8'));
manifest.dependencies.webcityeditor = `file:${tarball.replaceAll('\\', '/')}`;
await writeFile(join(consumer, 'package.json'), JSON.stringify(manifest, null, 2));
console.log(npm(['install', '--ignore-scripts', '--no-audit', '--no-fund'], consumer));
const installed = join(consumer, 'node_modules/webcityeditor');
const packageManifest = JSON.parse(await readFile(join(installed, 'package.json'), 'utf8'));
assert.equal(packageManifest.license, 'Apache-2.0');
assert.equal(packageManifest.dependencies, undefined);
console.log(npm(['exec', '--', 'webcityeditor-copy-assets', 'public/webcityeditor'], consumer));
// Refuse to overwrite arbitrary host content; only a marked copy accepts updates.
assert.throws(() => execFileSync(process.execPath, [join(installed, 'bin/copy-assets.mjs'), 'public/webcityeditor'], { cwd: consumer, stdio: 'pipe' }));
execFileSync(process.execPath, [join(installed, 'bin/copy-assets.mjs'), 'public/webcityeditor', '--update'], { cwd: consumer, stdio: 'inherit' });
const assets = await readdir(join(consumer, 'public/webcityeditor/assets'));
assert(assets.some(name => name.startsWith('osm2streets') && name.endsWith('.wasm')));
assert(assets.some(name => name.startsWith('web-ifc') && name.endsWith('.wasm')));
await writeFile(join(consumer, 'headless.mjs'), `import { parseCityJsonAuto, checkIntegrity, HAMBURG_ROAD_RULES } from 'webcityeditor/core';
import { createEditor } from 'webcityeditor';
import assert from 'node:assert/strict';
assert.equal(typeof window, 'undefined');
assert.equal(typeof createEditor, 'function');
const result = parseCityJsonAuto(JSON.stringify({type:'CityJSON',version:'2.0',CityObjects:{},vertices:[]}));
assert(result.ok); assert(checkIntegrity(result.doc).ok); assert(HAMBURG_ROAD_RULES.widths.bike_lane.minimumM > 0);
console.log('Headless Node imports passed');`);
execFileSync(process.execPath, ['headless.mjs'], { cwd: consumer, stdio: 'inherit' });
console.log(npm(['run', 'build'], consumer));
await writeFile(join(root, 'artifacts/consumer.json'), JSON.stringify({ consumer, tarball, size: packed.size, unpackedSize: packed.unpackedSize }, null, 2));
console.log(`Package consumer passed: ${consumer}\nTarball: ${tarball}\nPacked ${packed.size} bytes; unpacked ${packed.unpackedSize} bytes.`);
